- src/main/java/uk/gov/ons/census/casesvc/messaging/SampleReceiver.java
- src/main/java/uk/gov/ons/census/casesvc/model/dto/CollectionCase.java
The Action Scheduler might have complex Action Rules based on multiple attributes of a case, so we should send as much data as possible to enable these rules to be created.
Added a bunch of extra data from the sample, stored on the case, into the message which is emitted to RH & Action Processor via the fanout exchange.
Run the acceptance tests. Check the Action Scheduler case database and make sure all the rows are populated with data from the sample.
Trello: https://trello.com/c/R9CmkZGf/626-update-the-action-service-to-contain-new-attributes-8
> New case attributes send to Action Scheduler

- src/main/java/uk/gov/ons/census/casesvc/model/dto/Address.java
- src/main/java/uk/gov/ons/census/casesvc/model/dto/CollectionCase.java
- src/main/java/uk/gov/ons/census/casesvc/service/CaseProcessor.java
The case distribution messages were missing some case attributes, we need all attributes to be distributed.
- Include all current case attributes on case DTO
- Set all current case attributes when creating messages 
Run the acceptance tests against this branch and check the case messages which case-processor distributes, they should now contain all current attributes
https://github.com/ONSdigital/census-rm-action-scheduler/pull/4
https://trello.com/c/KMYeO526/738-defect-action-scheduler-is-missing-some-case-attributes-5
> Distribute all case attributes

- Dockerfile
- src/test/java/uk/gov/ons/census/casesvc/testutil/RabbitQueueHelper.java
Intermittent test failures, sendMessage in rabbitHelper may be retrying and sending multiple messages
Stopped rabbitHelper (test utility) retrying msg send
If there is a problem with the sendMessage the test should at least fail fast now, rather than give misleading results
https://trello.com/c/xX5tkSU0/778-case-processor-samplereceiverit-intermittent-failures
> Intermittent test failure

- src/main/java/uk/gov/ons/census/casesvc/model/entity/Case.java
- src/main/java/uk/gov/ons/census/casesvc/service/CaseProcessor.java
- src/main/java/uk/gov/ons/census/casesvc/utility/RandomCaseRefGenerator.java
- src/test/java/uk/gov/ons/census/casesvc/service/CaseProcessorTest.java
- src/test/java/uk/gov/ons/census/casesvc/utility/RandomCaseRefGeneratorTest.java
Case ref needs to be random rather than sequential because reasons.
Got rid of sequence generator and replaced with random number generator instead.
Load a sample. Check that all the case refs are random.
Trello: https://trello.com/c/ky7qtJCe
> Make caseRef randomy generated

- src/main/java/uk/gov/ons/census/casesvc/config/QueueSetterUpper.java
- src/main/resources/application.yml
Add UAC QID Created queue, exchange and binding config for ReabbitMQ.
QueueSetterUpper configuration.
Checkout branch
Checkout equivalent branch for Case-api
Check local Rabbit GUI for new Queue, Exchange and Binding.
https://github.com/ONSdigital/census-rm-case-api/pull/21/files
> Rmc 134 ad hoc fulfilment request consistency Queue Configuration

- src/main/java/uk/gov/ons/census/casesvc/config/MessageErrorHandler.java
- src/main/java/uk/gov/ons/census/casesvc/messaging/ActionSchedulerEventReceiver.java
- src/main/java/uk/gov/ons/census/casesvc/service/CaseService.java
- src/main/java/uk/gov/ons/census/casesvc/utility/QuestionnaireTypeHelper.java
- src/main/java/uk/gov/ons/census/casesvc/utility/Sha256Helper.java
- src/main/resources/application.yml
Without the stack traces, some of the errors would say little more than "Runtime exception" and be very hard to diagnose and fix.
Added descriptive text to all RuntimeExceptions. Added option to print stack traces which can be toggled on to diagnose difficult problems.
Try toggling the setting in application.yml and set off some exceptions.
Trello: https://trello.com/c/KViVYGvP
> Improve logging

- src/main/java/uk/gov/ons/census/casesvc/config/AppConfig.java
All rabbit channels should be transactional
updated the rabbit config in AppConfig.java to make sure all rabbit channels are transactional
start up service, go to the "channels" tab in the management UI and all channels from this app should be marked as transactional ("T" in the mode column)
> change config to make all rabbit channels transactional

- src/main/java/uk/gov/ons/census/casesvc/service/ReceiptService.java
We kaboom kablammo whenever we got a receipt for a QID which wasn't yet linked to a case.
Only update the case an emit update if there's one linked. Log a warning if there isn't.
Run the ATs with census-rm-docker-dev and Fieldwork Adapter built from branch decouple-questionnaire-linked.
Trello: https://trello.com/c/YBaj7soL
> Decouple questionnaire linked from receipting

- src/main/java/uk/gov/ons/census/casesvc/model/dto/CCSPropertyDTO.java
- src/main/java/uk/gov/ons/census/casesvc/service/CCSPropertyListedService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/CCSPropertyListedIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/TransactionsIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/CCSPropertyListedServiceTest.java
qid linking with CCSCaseListed
doesn't send out event if qid provided, tests for this
Install locally and try with AT branch: https://github.com/ONSdigital/census-rm-acceptance-tests/pull/137
https://trello.com/c/KNsTMSMf/1099-rmc-1663-handle-qid-linking-in-ccspropertylisted-event-5
> 1099 css with qid

- src/main/java/uk/gov/ons/census/casesvc/service/FulfilmentRequestService.java
- src/test/java/uk/gov/ons/census/casesvc/service/FulfilmentRequestServiceTest.java
This PR will allow an 'internal' fulfilment request from the case-api to generate a new HI case.
* Added new fulfilment code
* Update tests
Run acceptance tests against branches from the links in this PR 
https://github.com/ONSdigital/census-rm-case-api/pull/47
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/156
https://github.com/ONSdigital/census-rm-action-scheduler/pull/61
https://trello.com/c/UJpW7I1J/484-rmc-335-telephone-capture-hi-13
> RMC 335 Update fulfilment receiver for telephone capture HI cases

- src/main/java/uk/gov/ons/census/casesvc/model/dto/CollectionCase.java
- src/main/java/uk/gov/ons/census/casesvc/model/entity/Case.java
- src/main/java/uk/gov/ons/census/casesvc/service/CaseService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/census/casesvc/service/CaseServiceTest.java
- src/test/resources/application-test.yml
Added hand delivery flag to the cases table. As we don't have all the treatment codes finalised, I've just put an example one of what it could be just to prove it works.
- Added hand delivery flag
- Run `mvn clean install`
- Run with other branches and run acceptance tests.
https://trello.com/c/774V6fGU/580-add-handdelivery-flag-to-casecreated-and-caseupdated-events-and-case-api-8
> Added hand_delivery flag to cases

- src/main/java/uk/gov/ons/census/casesvc/service/RefusalService.java
- src/test/java/uk/gov/ons/census/casesvc/service/RefusalServiceTest.java
We want to record establishment address level case refusals that come from channels other than field but not update the case.
* Log estab non field refusals
* Update test
Build and run acceptance tests
https://trello.com/c/FcbMllGI/633-log-estab-individual-refusal-on-ce-and-spg-3
> Log establishment non-field refusals

- src/main/java/uk/gov/ons/census/casesvc/service/CaseReceiptService.java
- src/main/java/uk/gov/ons/census/casesvc/service/FulfilmentRequestService.java
- src/main/java/uk/gov/ons/census/casesvc/service/UacService.java
- src/main/java/uk/gov/ons/census/casesvc/utility/FormTypeHelper.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/QuestionnaireLinkedReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/ReceiptReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/TransactionsIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/CaseReceiptServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/FulfilmentRequestServiceTest.java
Complete receipting as per table: https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=SDC&title=Receipting
Refactor to use a table of Rules match the receipting table.  
Run the tests, the unit tests are hopefully very descriptive yet concise.
https://trello.com/c/w2DqzjyY/573-ce-and-spg-receipting-mark-case-as-receipted-13
> 573 receipting table

- src/main/java/uk/gov/ons/census/casesvc/service/EventService.java
- src/main/java/uk/gov/ons/census/casesvc/utility/QuestionnaireTypeHelper.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/SampleReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/utility/QuestionnaireTypeHelperTest.java
The sample load QID mappings need updating to be valid with the new receipting rules. This is not a final solution for these QIDs, just necessary for them to be valid in the interim.
* Update sample load QID mappings
* Update tests
Build this branch and run the AT's (no feature changes).
https://trello.com/c/7IpafPL9/653-bug-case-processors-sample-load-qid-generator-mappings-are-wrong
> Fix sample load qid mappings

- src/main/java/uk/gov/ons/census/casesvc/service/QuestionnaireLinkedService.java
- src/test/java/uk/gov/ons/census/casesvc/service/QuestionnaireLinkedServiceTest.java
Merged last case-processor PR without amending it as per Liam's suggestions
Specified UUID.class in QuestionnaireLinkedServiceTest
Assigned name for UUID.randomUUID() in QuestionnaireLinkedService
No changes to any functionality but clone branch and run ```mvn clean install``` to check it builds
https://trello.com/c/pKUaVF0i
> LT suggestions that I overlooked on last PR

- src/main/java/uk/gov/ons/census/casesvc/messaging/UndeliveredMailReceiver.java
- src/main/java/uk/gov/ons/census/casesvc/model/entity/Case.java
- src/main/java/uk/gov/ons/census/casesvc/service/CaseService.java
- src/main/java/uk/gov/ons/census/casesvc/service/NewAddressReportedService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/UndeliveredMailReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/UndeliveredMailReceiverTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/NewAddressReportedServiceTest.java
Undelivered as addressed marker has been removed
Undelivered as addressed marker removed along with any where it is set.
Build images for each of the repos on the trello ticket and run acceptance tests.
https://trello.com/c/gpxiNXHt/758-rmc-345-ce-and-spg-uaa-8
> Remove unaddressed as delivered flag

- src/main/java/uk/gov/ons/census/casesvc/model/dto/CollectionCase.java
Accidentally missed an undeliveredAsAddressed property (thanks Luke)
Removed the property
🙏 
https://trello.com/c/gpxiNXHt/758-rmc-345-ce-and-spg-uaa-8
> remove missed undelivered as addressed property

- src/main/java/uk/gov/ons/census/casesvc/model/dto/Address.java
- src/main/java/uk/gov/ons/census/casesvc/model/dto/CollectionCase.java
- src/main/java/uk/gov/ons/census/casesvc/model/dto/CreateCaseSample.java
- src/main/java/uk/gov/ons/census/casesvc/model/entity/Case.java
- src/main/java/uk/gov/ons/census/casesvc/service/CaseService.java
- src/main/java/uk/gov/ons/census/casesvc/service/NewAddressReportedService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/FulfilmentRequestReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/QuestionnaireLinkedReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/SampleReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/CaseServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/NewAddressReportedServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/testutil/DataUtils.java
Arid & Estab Arid being retired.  New Estab Uprn and Print Batch fields
Removed arid, removed estab_arid.  Added estab_uprn, added Print_batch
run ATs from branch with other bits installed
https://trello.com/c/zm2Ssvnn/771-make-sample-load-changes-to-meet-new-sample-spec-13
> 771 make sample load changes to meet new sample spec

- src/main/java/uk/gov/ons/census/casesvc/service/EventService.java
- src/main/java/uk/gov/ons/census/casesvc/utility/QuestionnaireTypeHelper.java
- src/test/java/uk/gov/ons/census/casesvc/service/EventServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/utility/QuestionnaireTypeHelperTest.java
Instead of using treatment code to derive the what the qid type is, we are now using case type and region instead.
- Calculate qid type by Case Type and Region
- Run mvn clean install
- Run with other branches and run the ATs
[Trello](https://trello.com/c/5NVWoFG9)
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/228
> 712 am1 part 7 new address telephone capture not ind

- src/test/java/uk/gov/ons/census/casesvc/testutil/DataUtils.java
There were some changes to the event dictionary which hadn't been reflected in the tests.
Tweak the tests.
Run the tests.
Trello: https://trello.com/c/4YXzoEXI
> Fix tests using outdated event JSON

- src/main/java/uk/gov/ons/census/casesvc/model/dto/NewAddress.java
Fix name of sourceCaseID to sourceCaseID.  Was previously wrong, though wasn't tested for as is not used yet.
Test with the new ATs
> change sourceCaseID to sourceCaseId in NewAddress Dto

- src/main/java/uk/gov/ons/census/casesvc/model/dto/FulfilmentInformation.java
Event dictionary changed an RM-interrnal event for undelivered mail.
Renamed productCode to fulfilmentCode
Play an undelivered mail scenario and check the logged payload in the event contains the fulfilment code.
Trello: https://trello.com/c/1kGNz8vl
> Rename productCode to fulfilmentCode

- src/main/java/uk/gov/ons/census/casesvc/utility/QuestionnaireTypeHelper.java
- src/test/java/uk/gov/ons/census/casesvc/utility/QuestionnaireTypeHelperTest.java
Want to generate individual addressed initial contact questionnaires for SPG Units in English and Welsh
New ActionTypes included
New unit test
Build and run with other repos and then run ATs
https://trello.com/c/nxTRcBaY/808-ic13-ic14-generate-spg-addressed-ic-pq-print-files-13
> IC13/IC14 Generate SPG Unit Addressed PQs

- src/main/java/uk/gov/ons/census/casesvc/service/BlankQuestionnaireService.java
- src/test/java/uk/gov/ons/census/casesvc/service/BlankQuestionnaireServiceTest.java
It was needlessly verbose before
Remove 10 zillion needless 'BlankQuestionnaireService.' prefixes and some annotations from the test 
> tidy blank questionnaire table to be more readable

- src/main/java/uk/gov/ons/census/casesvc/service/FulfilmentRequestService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/census/casesvc/messaging/FulfilmentRequestReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/FulfilmentRequestServiceTest.java
As part of handling individual fulfilment requests against non HH cases
checks for caseType == HH as well as individual pack code
> individuals against non HH cases handled

- src/main/java/uk/gov/ons/census/casesvc/service/CaseService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/census/casesvc/service/CaseServiceTest.java
- src/test/resources/application-test.yml
List of Hand Delivered (Direct Delivered) treatment codes
New list created
Removed dummy code from application.yml
Build the branch and check all tests pass
https://trello.com/c/AE3J1z9t/1187-update-hand-delivery-list-in-case-processor-2
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=SDC&title=Treatment+Codes+2021
> Hand Delivery Treatment Codes

- src/main/java/uk/gov/ons/census/casesvc/service/AddressModificationService.java
- src/test/java/uk/gov/ons/census/casesvc/service/AddressModificationServiceTest.java
Remove the thing.
Things.
Don't.
Trello: https://trello.com/c/J3wvm5Ma
> Remove estab type household validation

- src/main/java/uk/gov/ons/census/casesvc/model/dto/Address.java
- src/main/java/uk/gov/ons/census/casesvc/service/CaseService.java
Misspelling of abpCode
Corrected spelling
Build and run ATs in branch
https://trello.com/c/0TXN8vyT/1313-defect-attribute-abp-is-emitted-as-apb
> Change ABP attribute

- src/main/java/uk/gov/ons/census/casesvc/service/NewAddressReportedService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/AddressReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/NewAddressReportedServiceTest.java
We need to ensure the estabUprn is populated depending on a few different scenarios (see Trello ticket for further info on mappings).
* Added conditions to match scenarios 
* Added unit tests to cover different scenarios
Run with ATs in other branch
https://trello.com/c/I9f2nC5s/1338-populate-estabuprn-on-new-address-3
> 1338 - Populate estabUprn for new address

- src/main/java/uk/gov/ons/census/casesvc/model/dto/CCSPropertyDTO.java
- src/main/java/uk/gov/ons/census/casesvc/model/dto/SampleUnitDTO.java
- src/main/java/uk/gov/ons/census/casesvc/service/CCSPropertyListedService.java
- src/main/java/uk/gov/ons/census/casesvc/service/CaseService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/CCSPropertyListedIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/CCSPropertyListedServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/CaseServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/testutil/DataUtils.java
CCSPropertyListed has new InterviewRequired Flag.  It no longer should handle refusals, link qids, invalid etc
Changed class and some tests
and run ATs from ticket
https://trello.com/c/81w9gOMb/1130-ccs-handle-property-listing-events-2021-stylee-5
> 1130 ccs handle property listing events 2021 stylee

- src/main/java/uk/gov/ons/census/casesvc/utility/FormTypeHelper.java
Added the 62 qid type into form type helper so it's able to receipt on those qids
- Added the 62 qid type into form type helper 
- Run `mvn clean install`
- Run with AT branch and run the uncommented tests
[Trello](https://trello.com/c/vnrqfc8Z/)
> Added 62 qid form type to process receipt
