- src/main/java/uk/gov/ons/census/casesvc/config/AppConfig.java
- src/main/java/uk/gov/ons/census/casesvc/config/QueueSetterUpper.java
- src/main/java/uk/gov/ons/census/casesvc/messaging/UnaddressedReceiver.java
- src/main/java/uk/gov/ons/census/casesvc/model/dto/CreateUacQid.java
- src/main/java/uk/gov/ons/census/casesvc/service/UacProcessor.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/census/casesvc/messaging/SampleReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/SampleReceiverTest.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/UnaddressedReceiverTest.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/UnaddressedReceiverTestIT.java
- src/test/java/uk/gov/ons/census/casesvc/testutil/RabbitQueueHelper.java
We need to print a certain amount of letters, questionnaires, continuation pages etc. without an address. These will have an associated UAC/QID but no case - the case association will happen later. This PR covers the part where we generate the UAC/QID pair and emit the event to RH and Action Scheduler.
Created a new inbound queue called `unaddressedRequestQueue`. Process new JSON messages that arrive on new queue, issuing a UAC/QID pair without an associated case.
Run the acceptance tests from the same branch name (`rmc-176-uac-qid-pairs-for-unaddressed`) or run the new unaddressed batch runner (when it's completed).
Trello: https://trello.com/c/Hv7z7OqL/684-rmc-176-create-uac-qid-pairs-for-unaddressed-ccs-questionnaires-8
> Rmc 176 uac qid pairs for unaddressed

- src/main/java/uk/gov/ons/census/casesvc/messaging/UnaddressedReceiver.java
- src/main/java/uk/gov/ons/census/casesvc/model/entity/Event.java
- src/main/java/uk/gov/ons/census/casesvc/model/entity/EventType.java
- src/main/java/uk/gov/ons/census/casesvc/service/EventProcessor.java
- src/main/java/uk/gov/ons/census/casesvc/service/UacProcessor.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/UnaddressedReceiverTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/EventProcessorTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/UacProcessorTest.java
We need an event type stored against the case events to make it easier to find specific ones. The event types should come from a discrete enumerated list.
Added `EventType` enum and added it as a column to the `Event` entity.
Run ATs and check `event_type` DB column is populated in the `event` table in the case DB.
Trello: https://trello.com/c/ECRAB4bx
> Add EventType enum to Event

- Dockerfile
The docker image `openjdk:11-slim` has changed the location of the `java` binary.
Changed the `java` path to the correct one.
Build the image. Container should start.
Trello: https://trello.com/c/7ivpCfY6
Reasons why stuff got broken: https://github.com/docker-library/openjdk/issues/320#issuecomment-494417274
> Fix location of java after openjdk moved in docker image

- src/main/resources/application.yml
The agreed topic exchange name is "events" but its currently set to "case.outbound.exchange"
change outbound-exchange config item to "events"
run acceptance tests and everything should work as normal
> Change the topic exchange name to "events"

- src/main/java/uk/gov/ons/census/casesvc/config/QueueSetterUpper.java
- src/main/resources/application.yml
Currently the case.action queue has a wildcard as the routing key. This is causing the action-scheduler issues as it's trying to consume messages it can't.
Two routing keys are now bound to the action.case queue.
Build image off this branch, push to your GCR and deploy by tweaking [this line](https://github.com/ONSdigital/census-rm-kubernetes/blob/master/microservices/action-scheduler-deployment.yml#L37) to point at your pushed image. Check in rabbitmq management that the action.case queue has the following bindings:
**If you do not stop and start rabbitmq the old wildcard routing key will still be present, press the unbind button to get rid of it. This will also need to be done if deploying to any environment where rabbitmq is not restarted when deploying this change.**
Run the …
> Add specific routing keys for case.action to replace wildcard key

- .travis.yml
We are building and pushing our Docker images using Concourse instead of Travis. We need to stop Travis from pushing images, which are triggering extra deployments in Concourse which are not needed or wanted.
Removed the Docker image push from the Travis settings.
Merge to master. Travis shouldn't push to GCR.
Trello: https://trello.com/c/4chYCOrj
> Remove Docker image push from Travis build

- src/main/java/uk/gov/ons/census/casesvc/messaging/SampleReceiver.java
- src/main/java/uk/gov/ons/census/casesvc/messaging/UnaddressedReceiver.java
- src/main/java/uk/gov/ons/census/casesvc/service/CaseProcessor.java
- src/test/java/uk/gov/ons/census/casesvc/service/CaseProcessorTest.java
In the event of a case ref collision Hibernate is not throwing an ID not unique exception, but instead updating an existing entity, causing us to overwrite case data. We need to check that our ID is unique before we proceed with it and we need to flush it to the DB so that we guarantee that new cases are non-colliding.
Check for uniqueness of caseref. Use 'saveAndFlush' instead of 'save'.
Fill up the `cases` table with all possible caserefs using the SQL `INSERT INTO casev2.cases (case_ref) SELECT * FROM generate_series(10000000, 99999999);` and then ensure that the cases are valid using the SQL `update casev2.cases set receipt_received='f';`. Then try loading a sample - the messages should never be consumed from the `case.sample.inbound` queue and no messages should be published.
Trello: …
> Check for case ref collisons

- src/main/java/uk/gov/ons/census/casesvc/service/ReceiptProcessor.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/ReceiptReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/ReceiptProcessorTest.java
When a case receipt notification is received, the uac/qid link active state property is not persisted.
uac/qid link active state persisted to database
build local docker image from branch
run with docker dev
run tests
[Trello](https://trello.com/c/PVJDUlm5/985-deactivate-uac-qid-on-receipt-of-responsereceived-event-3)
> persist deactivation of uac/qid to database

- src/main/java/uk/gov/ons/census/casesvc/model/dto/UacDTO.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/QuestionnaireLinkedReceiverIT.java
"caseId" & "questionnaireId" should be the only fields serialised to the event_payload field.
Suppress null values in UacDTO
Changed UacDTO.active type to Boolean to allow null suppression
Improved Integration tests
Build local docker image of this branch and run with docker dev
Run tests
Run acceptance tests
[Acceptance Tests](https://github.com/ONSdigital/census-rm-acceptance-tests/pull/111)
[Trello](https://trello.com/c/2YY1TOKj/1068-extra-fields-being-shown-on-uac-object-when-qid-linked-event-stored)
> Suppress nulls in payload

- src/main/java/uk/gov/ons/census/casesvc/model/dto/ResponseDTO.java
Currently, the json payload in a Survey Launched event contains unreceipt: false. This should not be there.
The unreceipt type has been changed to Boolean (from boolean) to allow nulls so that it can be excluded from the json.
Run acceptance tests. Have a look in your DB for a survey launched event and see if "unreceipt": false is not present.
https://trello.com/c/H2V1Mb8f/1111-survey-launched-event-storing-unreceipt-flag-in-json-payload-in-case-events
> Set unreceipt flag to Boolean to stop being stored in event payload json

- src/main/java/uk/gov/ons/census/casesvc/service/UacService.java
We are currently using the addressType field from case data to populate the caseType field that is part of the uac_updated event that gets emitted, this should be using the recently added caseType field
Changed code to set the caseType field on the uac_updated event from the caseType field from the case data
- run acceptance tests
> use caseType not addressType to set the caseType field in uac_updated message

- Dockerfile
- src/main/java/uk/gov/ons/census/casesvc/config/AppConfig.java
- src/main/java/uk/gov/ons/census/casesvc/config/MessageErrorHandler.java
We can't handle messages from FWMT due to strict JSON checking
Disabled strict JSON checking.
Hard to reproduce, but try this message:
```
{"event":{"type":"FULFILMENT_REQUESTED","source":"FIELDWORK_GATEWAY","channel":"FIELD","dateTime":"2019-09-13T14:22:34.327Z","transactionId":"3287c518-1898-406c-b55e-1e6138678550"},"payload":{"fulfilmentRequest":{"fulfilmentCode":"P_OR_H1","caseId":"02606dca-7f75-e911-abc4-0003ff39541c","address":{},"contact":{"title":null,"forename":null,"surname":null,"telNo":null}}}}
```
Trello: https://trello.com/c/MKGPgxP8
> Fix for strict JSON checking

- src/test/resources/definitions.json
Updated the queue binding for questionnaire linked events to match the one in the event dictionary.
Updated the Rabbit queue binding
- Unit tests should pass
- Locally, run the `update-queue-binding-for-questionnaire-linked-event` branch of acceptance tests, using `update-queue-binding-for-questionnaire-linked-event` branch of docker-dev and this branch of case-processor
- Run in kubernetes using `update-queue-binding-for-questionnaire-linked-event` branch
> Update the queue binding for questionnaire linked events

- src/main/java/uk/gov/ons/census/casesvc/model/dto/CCSPropertyDTO.java
- src/main/java/uk/gov/ons/census/casesvc/service/CCSPropertyListedService.java
- src/main/java/uk/gov/ons/census/casesvc/service/CaseService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/CCSPropertyListedIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/CCSPropertyListedServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/CaseServiceTest.java
Handle a ccsPropertyListed event Refusal outcome
Mark case as refused
Do not notify FWMT if refused
create local docker image of this branch and attached pr and run using docker-dev
run tests
[Trello](https://trello.com/c/DGGOf9tf/1101-rmc-1664-handle-a-refusal-in-a-ccspropertylisted-event-5)
[census-rm-acceptance-tests](https://github.com/ONSdigital/census-rm-acceptance-tests/pull/139)
> Handle a refusal in a CCSPropertyListed event

- src/main/java/uk/gov/ons/census/casesvc/model/dto/CCSPropertyDTO.java
- src/main/java/uk/gov/ons/census/casesvc/service/CCSPropertyListedService.java
- src/main/java/uk/gov/ons/census/casesvc/service/CaseService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/CCSPropertyListedIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/CCSPropertyListedServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/CaseServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/testutil/DataUtils.java
Handle a CCSPropertyListed Event with an Invalid Address attached
Added code and tests to handle InvalidAddress
Removed DirtiesContext from CCS ITs
install locally and run with same AT branch
https://github.com/ONSdigital/census-rm-acceptance-tests/tree/1103-rmc-1665-handle-an-invalid-address-ccs
https://trello.com/c/quLd0TdT/1103-rmc-1665-handle-an-invalid-address-in-a-ccspropertylisted-event-5
> handles CCS Invalid Address

- src/main/java/uk/gov/ons/census/casesvc/service/CCSPropertyListedService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/CCSPropertyListedIT.java
Always create a new uac-qid pair when a CCS property listed event is received. This is because a CCS PQ may be linked but not completed and if a field agent calls on property again they will need a uac-qid to launch an EQ.
Small code change to always create uac-qid
Build locally and run in docker-dev then run acceptance tests
https://trello.com/c/TRtVJEzn/1268-qid-linked-in-property-listing-event-should-create-a-uac-qid-pair-by-default-on-case-creation-3
> Always create uac-qid pair for CCS property listed event.

- src/main/java/uk/gov/ons/census/casesvc/config/MessageConsumerConfig.java
This change was made on a branch, but because of the CCS changes it was too much of a nightmare to merge, so I've just made a new branch, because it's just a 1-line change.
Put the correct service name in.
It's already been tested. It's already live.
Nope
> Service name was wrong for Exception Manager

- src/main/java/uk/gov/ons/census/casesvc/messaging/ManagedMessageRecoverer.java
Msgs sent to delay or delivery weren't set as Persistent, so on a rabbit restart they'd be lost
Make msgs sent to delay or quarantine Persistent, deliveryMode wasn't set by default.
Also removed unneeded bool settings around result.
Build this branch locally, tag it & push to your GCP.  Using rabbit GUI send 2 bad msgs to case-processor, i.e. case.ccsPropertyListedQueue.  Then with the toolbox use msgWizard to quarantine 1 of the msgs.  If you now look on the delayedRedeliveryQueue & the quarantineQueue there should be 1 msg on each marked persistent.
Then in your workloads drill into rabbitmq and scale down to 0 from 3.  Then when completed scaling down, scale back up to 3.  Wait till all green then navigate back to the RabbitUI,  there should be a persistent msg in Quarantine and 1 on …
> Make Quarantined & delayedRetry messages persistent

- Dockerfile
Running docker containers in root is a security concern so there should be a user that's created that the container can use instead. 
- Added a non-root user
- Updated dockerfile layout
- Run mvn clean install
- Run in docker dev environment with other prs
- Run in kubernetes environment with other prs
[Trello](https://trello.com/c/dUT7y0TW)
> Making dockerfile non root

- src/main/java/uk/gov/ons/census/casesvc/config/MessageConsumerConfig.java
- src/main/java/uk/gov/ons/census/casesvc/messaging/ManagedMessageRecoverer.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/census/casesvc/messaging/ManagedMessageRecovererTest.java
- src/test/resources/definitions.json
We need to make RabbitMQ responsible for routing bad messages to a DLQ instead of manually doing this in our application code. This PR makes use of `AmqpRejectAndDontRequeueException` to reject a bad message, allowing Rabbit to take care of routing and redelivering that message.
* Reject the message by throwing an exception
* Remove retry exchange from code 
* Suppress 'noisy' stack trace logging at warning level when the exception is thrown
*  Update tests and test queue config
Build this branch, checkout the [docker-dev PR](https://github.com/ONSdigital/census-rm-docker-dev/pull/40) and post a bad message to a queue this service consumes from. Check the message is redelivered continuously.
https://trello.com/c/hG9Mi8tA/315-rabbit-message-persistence-dlq-config-8
> Rabbit msg persistence dlq config

- src/main/java/uk/gov/ons/census/casesvc/model/dto/CollectionCase.java
- src/main/java/uk/gov/ons/census/casesvc/model/entity/Case.java
- src/main/java/uk/gov/ons/census/casesvc/service/CaseService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/SampleReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/CaseServiceTest.java
CE cases to be sent to field
Set the CaseType Correctly from AddressType
On the case Entity:
Change ceExpectedCapacity to be an Integer, we will soon want to compare to ceActualResponses
Add ceActualResponses as an Integer
And with the other applications installed with the AT branch from:
https://trello.com/c/i8X8YCZM/452-rmc-317-send-ce-estab-job-to-field-13
> 452 rmc 317 send ce estab job to field

- src/main/java/uk/gov/ons/census/casesvc/service/ReceiptService.java
- src/main/java/uk/gov/ons/census/casesvc/utility/QuestionnaireTypeHelper.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/ReceiptReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/ReceiptReceiverTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/ReceiptServiceTest.java
Don't want the continuation questionnaire types to get a receipt received 
Identified QID first 2 digits that relate to continuation types that wont receive a receipt and created a test for it
Clone repo and check it works on machine
https://trello.com/c/fcEkdqbL
https://collaborate2.ons.gov.uk/confluence/display/SDC/Receipting+of+Continuation+Questionnaires
> Don't receipt continuation questionnaire types

- src/main/java/uk/gov/ons/census/casesvc/model/dto/CreateCaseSample.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/SampleReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/CaseServiceTest.java
When a sample unit has a blank CE_EXPECTED_CAPACITY in the sample file, case processor cannot ingest it and rejects the message. This change is to enable case processor to accept these sample units. 
ceExpectedCapacity changed to Integer in CreateCaseSample.
Unit test updated to allow this and is also checked in an integration test.
Maven clean install
Run [acceptance tests on branch of the same name](https://github.com/ONSdigital/census-rm-acceptance-tests/pull/157) - they should pass.
Run performance tests - they should pass now.
Push case processor image to your GCP if you fancy, then run acceptance tests and performance tests.
https://trello.com/c/iPx9qCU5/495-fix-sample-files-or-sample-file-loading-for-ceexpectedcapacity-3
> fix sample loading for ceExpectedCapacity

- src/main/java/uk/gov/ons/census/casesvc/utility/QuestionnaireTypeHelper.java
- src/test/java/uk/gov/ons/census/casesvc/utility/QuestionnaireTypeHelperTest.java
Handle SPG cases - they'll be assigned to the standard HH questionnaire types
If it's an SPG case (i.e. the treatment code starts with `SPG` then it'll be linked to a HH questionnaire type, like a standard HH case type.
- All unit and integration tests should pass
- Run the SPG branch of the acceptance tests with this branch --> https://github.com/ONSdigital/census-rm-acceptance-tests/pull/158
- https://trello.com/c/1IB69qys
> Assign SPG case types to household questionnaires

- src/main/java/uk/gov/ons/census/casesvc/model/entity/Case.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/RefusalReceiverIT.java
Adding this lastUpdated time stamp will provide the capability to do 'delta' based extracts from RM for data that is sent to DAP for use by processing and the RCA/FPA algorithms as opposed to exported the full set each time.
lastUpdated column added to Case entity, this is annotated so that the lastUpdated time is updated when the row is updated.
An integration test has been modified to check that the lastUpdated is different from when a case is created and it is updated with a refusal event.
Build case processor, run acceptance tests. 
Get some data in your database and check the last_updated column for a specific case. Submit a message to rabbitmq that will update this case (refusal, receipt etc) and check the last_updated field has changed. …
> Add last updated column to case entity

- src/main/java/uk/gov/ons/census/casesvc/messaging/UacCreatedEventReceiver.java
- src/main/java/uk/gov/ons/census/casesvc/model/dto/FulfilmentRequestDTO.java
- src/main/java/uk/gov/ons/census/casesvc/service/FulfilmentRequestService.java
- src/main/java/uk/gov/ons/census/casesvc/service/UacService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/FulfilmentRequestReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/RefusalReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/UacCreatedEventReceiverTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/FulfilmentRequestServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/UacServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/testutil/DataUtils.java
The order that we received the UAC created and fulfilment messages resulted in either success or failure. Given that we have no control over which message we process first, we needed to refactor.
Combined the UAC-QID created details into the fulfilment message, so it can be linked to a new case, should one need to be created.
Run the acceptance tests. There should be zero regression (and a whole lot less errors in the logs).
Trello: https://trello.com/c/yNjry5aD
> Refactor to handle new UAC-QIDs as part of fulfilment messages

- src/main/java/uk/gov/ons/census/casesvc/model/dto/CollectionCase.java
- src/main/java/uk/gov/ons/census/casesvc/model/entity/Case.java
- src/main/java/uk/gov/ons/census/casesvc/model/entity/CaseState.java
- src/main/java/uk/gov/ons/census/casesvc/service/CaseService.java
- src/main/java/uk/gov/ons/census/casesvc/service/FulfilmentRequestService.java
- src/test/java/uk/gov/ons/census/casesvc/service/CaseServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/FulfilmentRequestServiceTest.java
We can now safely remove the redundant case `state` column from our schemas.
Removed `state` from the repo
Make sure tests and acceptance tests still pass from the links below
https://trello.com/c/dBJe87ZS/481-get-rid-of-casestate-from-case-table-8
https://github.com/ONSdigital/census-rm-case-api/pull/53
https://github.com/ONSdigital/census-rm-action-scheduler/pull/64
https://github.com/ONSdigital/census-rm-action-worker/pull/9
https://github.com/ONSdigital/census-rm-ddl/pull/32
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/169
> Remove case state

- src/main/java/uk/gov/ons/census/casesvc/service/QuestionnaireLinkedService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/QuestionnaireLinkedReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/QuestionnaireLinkedServiceTest.java
SPG & CE cases shouldn't create child HI cases when we link unaddressed questionnaires.
Limited individual case creation to HH cases only.
Run the ATs.
Trello: https://trello.com/c/GJvtm94j
> Qid linking to non hh cases

- src/main/java/uk/gov/ons/census/casesvc/service/RefusalService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/RefusalReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/RefusalServiceTest.java
We need to throw a RunTimeException if we receive a refusal message for an estab address level case from a non-Field channel, which shouldn't happen. This is to allow ops support to identify which channel sent the message (as we're only expecting these to come from Field).
Add check after retrieving the case to see if the address level is `E`.
Run maven build and acceptance tests against the links in this PR. There should be no regression.
https://trello.com/c/i0aebEJC/534-handle-ce-and-spg-refusals-for-estab-address-level-cases-5
https://github.com/ONSdigital/census-rm-fieldwork-adapter/pull/27
> Handle estab address level refusal

- src/main/java/uk/gov/ons/census/casesvc/messaging/UndeliveredMailReceiver.java
- src/main/java/uk/gov/ons/census/casesvc/model/dto/ActionInstructionType.java
- src/main/java/uk/gov/ons/census/casesvc/model/dto/Metadata.java
- src/main/java/uk/gov/ons/census/casesvc/model/dto/PayloadDTO.java
- src/main/java/uk/gov/ons/census/casesvc/service/CaseReceiptService.java
- src/main/java/uk/gov/ons/census/casesvc/service/CaseService.java
- src/main/java/uk/gov/ons/census/casesvc/service/EventService.java
- src/main/java/uk/gov/ons/census/casesvc/service/InvalidAddressService.java
- src/main/java/uk/gov/ons/census/casesvc/service/QidReceiptService.java
- src/main/java/uk/gov/ons/census/casesvc/service/QuestionnaireLinkedService.java
- src/main/java/uk/gov/ons/census/casesvc/service/RefusalService.java
- src/main/java/uk/gov/ons/census/casesvc/utility/EventHelper.java
- src/main/java/uk/gov/ons/census/casesvc/utility/MetadataHelper.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/InvalidAddressReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/ReceiptReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/RefusalReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/UndeliveredMailReceiverTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/CaseReceiptServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/CaseServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/EventServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/InvalidAddressServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/QidReceiptServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/QuestionnaireLinkedServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/RefusalServiceTest.java
We are refactoring the way unscheduled field notifications are sent. The fieldwork adapter now subscribes to case events and sends whatever field notification is specified by a new fieldDecision metadata field.
* Add metadata DTO and action instruction type enum
* Set field instruction and cause event type on receipts, refusals and address invalid case updated events
* Don't set field decision if it is  if the source channel of refusal and invalid address events is field
* Update unit tests
Build and run with the linked branches of docker dev, fieldwork adapter, acceptance tests
https://trello.com/c/K9lfLHAs/609-refactor-fieldwork-receipting-21
https://github.com/ONSdigital/census-rm-fieldwork-adapter/pull/29
https://github.com/ONSdigital/census-rm-docker-dev/pull/48 …
> Use case events for unscheduled field notifications

- src/main/java/uk/gov/ons/census/casesvc/service/CaseService.java
- src/test/java/uk/gov/ons/census/casesvc/service/CaseServiceTest.java
We were getting null pointer exceptions because the address builder relied on region being set
* Allow null region in address DTO builder
* Add unit test
Build and run acceptance tests
https://trello.com/c/1F5lJNLo/630-ccs-refusal-messages-fail-in-case-processor
> Allow null region in address DTO builder

- src/main/java/uk/gov/ons/census/casesvc/model/dto/UacDTO.java
- src/main/java/uk/gov/ons/census/casesvc/service/UacService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/TransactionsIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/UacServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/testutil/DataUtils.java
RH wanted a value which could be derived from another value, so we implemented this in RM instead of RH.
Derived the form type from the questionnaire type. Sent it in the UACUpdated message to RH.
Run the acceptance tests.
Trello: https://trello.com/c/nGDQ3eJF
> Added derived form type for the amusement of RH

- src/main/java/uk/gov/ons/census/casesvc/model/dto/CcsToFwmt.java
- src/main/java/uk/gov/ons/census/casesvc/service/CcsToFieldService.java
- src/test/java/uk/gov/ons/census/casesvc/service/CcsToFieldServiceTest.java
As we're (currently) including the `handDelivery` flag on all outgoing messages to fieldwork, we need to make sure this is also set for CCS cases as well.
Add handDelivery attribute to CCS to FWMT bits
Run against branches below
https://trello.com/c/esdStYzJ/514-rmc-317-make-hand-delivery-flag-in-outbound-field-messages-dynamic-based-on-treatment-code-8
ONSdigital/census-rm-fieldwork-adapter#30
ONSdigital/census-rm-acceptance-tests#191
ONSdigital/census-rm-ddl#38
ONSdigital/census-rm-action-worker#10
https://github.com/ONSdigital/census-rm-action-scheduler/pull/65
> Add handDelivery to outbound CCS msgs

- src/main/java/uk/gov/ons/census/casesvc/service/CaseReceiptService.java
- src/main/java/uk/gov/ons/census/casesvc/utility/FormTypeHelper.java
Was returning a Cont for Continuation Types from FormTypeHelper, should be null
returns null from FormTypeHelper for Continuation Types
With master ATs
> stop return Cont from FormTypeHelper

- src/main/java/uk/gov/ons/census/casesvc/model/dto/CCSPropertyDTO.java
- src/main/java/uk/gov/ons/census/casesvc/service/CCSPropertyListedService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/CCSPropertyListedIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/CCSPropertyListedServiceTest.java
We should allow linking of multiple QIDs when we receive a CCS property listed event
Allow multiple QIDs in the `uac` block on a CCS message, linking each of these on receiving
Ensure the branch builds. Run ATs against the branch linked below
https://trello.com/c/OxvWc8A3/317-handle-multiple-qid-links-for-ccs-property-listings-8
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/205
> Handle multiple QIDs for CCS

- src/main/java/uk/gov/ons/census/casesvc/model/entity/Case.java
- src/main/java/uk/gov/ons/census/casesvc/model/entity/Event.java
- src/main/java/uk/gov/ons/census/casesvc/model/entity/UacQidLink.java
Hibernate does not set up the same database config in a dev GCP env as it does in an env built from the DDL scripts.
Fixed mismatches.
Build and run into empty database. Using a **reliable** DB inspection tool (i.e. not DataGrip) check the missing indexes are present.
Trello: https://trello.com/c/ybEYuI66
> Add missing indexes and fix other DDL mismatch

- src/main/java/uk/gov/ons/census/casesvc/service/CaseReceiptService.java
- src/test/java/uk/gov/ons/census/casesvc/service/CaseReceiptServiceTest.java
When we reach the number of actual responses for a Communal Establishment Unit (e.g. a university halls of residence dorm) then we want to send FWMT a CLOSE instead of an UPDATE.
Created a new bespoke rule which kindly does the needful.
Run the ATs.
Create a CE U case with an expected response count of 2. Link 2 uac-qid pairs to the case. Receipt the QIDs. When the second QID is receipted, a FWMT CLOSE should be sent.
Trello: https://trello.com/c/GapIaH4L
> Send CLOSE to FWMT for CE U where AR >= ER

- src/main/java/uk/gov/ons/census/casesvc/service/QuestionnaireLinkedService.java
- src/test/java/uk/gov/ons/census/casesvc/service/QuestionnaireLinkedServiceTest.java
We want to change how we had questionnaire links if the QID in question as already been linked to a different case so that it logs an error but does re-link the QID.
* Log and relink on QID link that has already been linked
Build and run acceptance tests (for regression).
To test the feature, load an unaddressed batch, post in a link for a QID from the batch, then post in a link for the same QID with a different case ID. The case processor should now log and error but continue to relink the QID.
https://trello.com/c/8VjhtXme/717-overwrite-case-id-if-duplicate-pq-link-qid-event-arrives-5
> Allow Overwriting QID Links

- src/main/java/uk/gov/ons/census/casesvc/messaging/UndeliveredMailReceiver.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/UndeliveredMailReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/UndeliveredMailReceiverTest.java
UAA fieldwork updates will now be handled through the case processor field decision on case updated events.
* Set field decision CREATE on UAA case updates
Build and run AT's with other linked branches
https://trello.com/c/1EAHHRAR/635-rmc-345-ce-and-spg-uaa-5
https://github.com/ONSdigital/census-rm-docker-dev/pull/50
https://github.com/ONSdigital/census-rm-action-scheduler/pull/70
https://github.com/ONSdigital/census-rm-kubernetes/pull/214
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/214
> Set field decision CREATE on UAA case updates

- src/main/java/uk/gov/ons/census/casesvc/model/dto/ActionInstructionType.java
- src/main/java/uk/gov/ons/census/casesvc/service/CaseReceiptService.java
- src/main/java/uk/gov/ons/census/casesvc/service/InvalidAddressService.java
- src/main/java/uk/gov/ons/census/casesvc/service/RefusalService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/AddressReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/ReceiptReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/RefusalReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/CaseReceiptServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/InvalidAddressServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/RefusalServiceTest.java
Better wording - less ambiguous 
Any reference to a CLOSE event has been changed to CANCEL
Clone branch and build/test it
https://trello.com/c/3PljKzC2/770-change-field-close-message-to-cancels-5
> Changed CLOSE to CANCEL

- src/main/java/uk/gov/ons/census/casesvc/model/dto/CollectionCase.java
- src/main/java/uk/gov/ons/census/casesvc/service/NewAddressReportedService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/census/casesvc/messaging/AddressReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/NewAddressReportedServiceTest.java
Now have an explicit table to map from event to skeleton case: https://collaborate2.ons.gov.uk/confluence/display/CATD/Census+Case+Processor#CensusCaseProcessor-NewAddressReported
Changed to code to match new table
Everything else on master, mvn clean install and run ATs
Check some mandatory fields Region, id, addressType, addressLevel missing error msgs.  Had an error I can't reproduce with these (wrong error msg).  Was probably due to dirty local environment, but would appreciate further eyes on this.
{
"event":{
"type":"NEW_ADDRESS_REPORTED",
"source":"FIELDWORK_GATEWAY",
"channel":"sender",
"dateTime":"2011-08-12T20:17:46.384Z",
"transactionId":"d9126d67-2830-4aac-8e52-47fb8f84d3b9"
},
"payload":{
"newAddress":{
"collectionCase":{
"id":"beeb3cb8-e24d-46b6-bcf1-6f5cff561b04", …
> 791 am1 why are some fields copied error msgs for missing fields

- src/main/java/uk/gov/ons/census/casesvc/messaging/UndeliveredMailReceiver.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/SurveyLaunchedReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/UndeliveredMailReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/UndeliveredMailReceiverTest.java
An UPDATE message is still being emitted to field when an undelivered_mail_reported event is ingested
This should not happen if the case is marked as either receipted, refused, invalid or NI CE
New criteria added for when an UPDATE message is not sent
Creation of unit test to cover all scenarios where an UPDATE message is not sent
Had to couple other integration tests to set receipt/refusal/invalid to false
Run and tests locally and check image builds
https://trello.com/c/hkArUv0E/807-dont-update-field-on-undeliveredmailreported-event-when-case-has-been-receipted-refused-etc-5
> Changing criteria for when an UPDATE message is sent to field

- src/main/java/uk/gov/ons/census/casesvc/messaging/AddressReceiver.java
- src/main/java/uk/gov/ons/census/casesvc/model/dto/NewAddress.java
- src/main/java/uk/gov/ons/census/casesvc/service/NewAddressReportedService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/AddressReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/AddressReceiverTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/NewAddressReportedServiceTest.java
New address events can be submitted that include a case id from an existing case. A number of fields can be copied from either the event or source case, depending whether they are present in the event. There are also a number of fields that do not come on the event, but can either be copied from the source case or not.
New method to build a case from a new address event and source case, taking the fields from the appropriate source depending on presence.
Tests updated and some added.
Build branch, and [test with acceptance tests on the same branch name](https://github.com/ONSdigital/census-rm-acceptance-tests/pull/235). Check the tables in the confluence document linked from Trello, and the confluence doc linked from that doc. Check that these tables match up with how the new case is …
> Am1 part2 new address using source case

- src/main/java/uk/gov/ons/census/casesvc/service/NewAddressReportedService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/AddressReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/NewAddressReportedServiceTest.java
If a new address event came in with a source case Id, the new case wasn't being set as a skeleton case. Also, the case metadata needed copying over (at the moment, only secure establishment).
New case has its skeleton flag ticked.
Method added to set the case metadata (might be useful for future if more properties are added to the case metadata. If there is something in the case metadata we don't want being copied into the new case, we can set here).
Tests updated.
maven clean install, run alongside acceptance tests on branch of [the same name](https://github.com/ONSdigital/census-rm-acceptance-tests/pull/239).
https://trello.com/c/2pT2lf1x/874-add-more-fields-from-source-case-id-upon-receiving-newaddressreported-3
> set new case to skeleton and copy metadata over

- src/main/java/uk/gov/ons/census/casesvc/messaging/UndeliveredMailReceiver.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/UndeliveredMailReceiverTest.java
There was a defect which was stopping English and Welsh CE cases being sent to field when we receive an Undelivered As Addressed message.
Fixed the bug. Improved the tests.
Run the tests.
Trello: https://trello.com/c/tUUaxWm6
> Send update to field for CE cases when UAA

- src/main/java/uk/gov/ons/census/casesvc/service/NewAddressReportedService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/AddressReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/NewAddressReportedServiceTest.java
When a newAddress reported has no Long/Lat on the event, if it has a source case copy them from that
Copies source rather than null for lat/long
& with ATs on card
https://trello.com/c/nPtXCwKt/910-copy-lat-long-from-source-case-id-overwrite-with-anything-on-event-3
> 910 copy lat long from source case id overwrite with anything on event

- src/main/java/uk/gov/ons/census/casesvc/model/dto/UacDTO.java
- src/main/java/uk/gov/ons/census/casesvc/service/QuestionnaireLinkedService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/QuestionnaireLinkedReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/ReceiptReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/QuestionnaireLinkedServiceTest.java
When a PQ link event comes in with an individual QID, and the parent case is a HH, the event carries an individualCaseId to set the created HIs cases case_id.
Logic added to check what is required to create a HI case, and error where things are missing. Tests updated and added.
Build branch and run with acceptance tests on [branch of the same name](https://github.com/ONSdigital/census-rm-acceptance-tests/pull/247).
https://trello.com/c/pquWVfXV/835-create-hi-case-for-individual-pq-link-event-8
> Changes to add individual case id for PQ link event for HIs

- src/main/java/uk/gov/ons/census/casesvc/service/CaseService.java
- src/test/java/uk/gov/ons/census/casesvc/service/CaseServiceTest.java
Child cases from skeleton cases should be marked as such
* Copy over skeleton marker when creating a child individual case
Run the new AT for individual telephone capture on newly reported address, check the skeleton flag is set in the DB on the HI case created
https://trello.com/c/zwSsVjsD/713-am1-part-71-new-address-create-hi-case-for-telephone-capture-3
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/249
> AM1 7.1 new address HI telephone capture

- src/main/java/uk/gov/ons/census/casesvc/model/dto/SampleUnitDTO.java
Some places in the event dictionary used fieldofficerId & fieldcoordinatorId (note lowercase letters) when RM uses fieldOfficerId & fieldCoordinatorId
Need to have it changed to camelCase
Typo changes in JSON in SampleUnitDTO
Build and view output after tests are run
https://trello.com/c/hdCMxP1S/883-fieldcoordinatorid-fieldofficerid-need-to-use-standardised-camel-case-across-census-3
> Standardising Wording to camelCase

- src/main/java/uk/gov/ons/census/casesvc/model/entity/Event.java
- src/main/java/uk/gov/ons/census/casesvc/model/entity/UacQidLink.java
Case API was performing very badly when retrieving case events.
Added indexes to both `uac_qid_link` and `event` table to prevent table-scanning.
Load large sample. Call case API including `?caseEvents=true`. It should be fast response time.
Trello: https://trello.com/c/fHPtdl59
> Add missing indexes to improve performance

- src/main/java/uk/gov/ons/census/casesvc/model/dto/RefusalDTO.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/RefusalReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/RefusalReceiverTest.java
We want to be able to capture a callId sent from CC/Field on refusals because reasons.
Added the callId to the DTO.
Send in a refusal including a callId. Check the event table to make sure it got persisted.
Trello: https://trello.com/c/ZwNBjX2s
> Capture callId on refusals

- src/test/java/uk/gov/ons/census/casesvc/messaging/ActionSchedulerEventReceieverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/AddressReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/CCSPropertyListedIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/FulfilmentConfirmedReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/FulfilmentRequestReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/QuestionnaireLinkedReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/ReceiptReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/RefusalReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/SampleReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/SurveyLaunchedReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/TransactionsIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/UacCreatedEventReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/UnaddressedReceiverTestIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/UndeliveredMailReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/testutil/QueueSpy.java
- src/test/java/uk/gov/ons/census/casesvc/testutil/RabbitQueueHelper.java
The case processor integration tests were slowing down the build more and more, with it taking in excess of 7 minutes. Also, lots of tests had to 'dirty' the Spring context in order to work reliably, which was an ugly hack.
Handle the cleanup of temporary queue listeners neatly and elegantly, such that tests which listen to the same queue don't end up consuming other tests' messages.
Should be like-for-like... only QUICKER!
Trello: https://trello.com/c/zrCqMG4A
> Fix flakey slow integration tests

- src/test/java/uk/gov/ons/census/casesvc/messaging/CCSPropertyListedIT.java
RM makes no guarantee about the order which it'll process events. As such, we cannot assume the order of things in our tests.
Fixed test which assumed the order of events.
Run a billion times in Travis. If it works, it might still be wrong. Maybe it will fail months later.
Nope
> Fix flakey test which assumed order of items in list

- src/main/java/uk/gov/ons/census/casesvc/service/QuestionnaireLinkedService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/QuestionnaireLinkedReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/QuestionnaireLinkedServiceTest.java
Currently if a questionnaire linked event comes in with an individual case id present and the parent case is CE/SPG, it'll chuck an error. We now want to link the questionnaire to the parent case and ignore the individual case id.
Error chucking stuff removed. Tests updated.
Build the branch. Test the branch with the [acceptance tests on the branch of the same name.](https://github.com/ONSdigital/census-rm-acceptance-tests/pull/273)
https://trello.com/c/V7O2qqSV/1017-pq-link-ignore-individual-case-id-if-parent-case-is-not-hh-5
> link questionnaire to CE/SPG parent case even if ind case Id is present

- src/main/java/uk/gov/ons/census/casesvc/service/CaseReceiptService.java
- src/test/java/uk/gov/ons/census/casesvc/service/BlankQuestionnaireServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/CaseReceiptServiceTableTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/CaseReceiptServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/QidReceiptServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/QuestionnaireLinkedServiceTest.java
The CE actual response count should be incremented regardless of whether the case is receipted or not.
* Always look up and run the receipting rule
* Check receipted status in receipting rules
Build and run linked AT's
https://trello.com/c/bhDgGx3H/1035-defect-ceactualresponse-count-not-increasing-for-ce-case
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/275
> Always increment CE actual response count where applicable 

- src/main/java/uk/gov/ons/census/casesvc/service/NewAddressReportedService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/census/casesvc/messaging/AddressReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/NewAddressReportedServiceTest.java
If a new address event is ingested (with source case or without), unless a UPRN is on the event then there isn't one set. This PR adds functionality to apply a dummy PR to the new case.
Logic added to apply dummy UPRN if no uprn present. The dummy UPRN consists of a prefix and the case ref, so this UPRN has to be added after the new case is saved/
Build the branch. Run the branch with the [acceptance tests on the branch of the same name](https://github.com/ONSdigital/census-rm-acceptance-tests/pull/286).
https://trello.com/c/nVFvsv29/1025-apply-dummy-uprn-5
> Apply dummy uprn on new address if not present on event

- src/main/java/uk/gov/ons/census/casesvc/client/ExceptionManagerClient.java
- src/main/java/uk/gov/ons/census/casesvc/messaging/ManagedMessageRecoverer.java
- src/main/java/uk/gov/ons/census/casesvc/model/dto/ExceptionReport.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/ManagedMessageRecovererTest.java
When we get errors like null pointer exceptions, it's often unclear where exactly in the code things have gone wrong. The stacktrace has the detail, but we don't log stacktraces by default, and stack traces are often laborious to trawl through.
Added code to trawl the stacktrace and extract the 'root cause' in our code of where the NPE or other type of exception originated from, which should allow us to more quickly diagnose & fix problems.
Send in a bad message (missing some mandatory data, for example) and check the logs - there should be details about the line of code which threw the exception (NOT the cause... the RESULT of bad data being sent into RM which shouldn't happen but does happen when we're testing).
Trello: https://trello.com/c/DQgYqRA8
> Log useful stacktrace line

- src/main/java/uk/gov/ons/census/casesvc/service/CaseReceiptService.java
- src/test/java/uk/gov/ons/census/casesvc/service/CaseReceiptServiceTableTest.java
There's a possibility that ceExpectedCapacity could be null. When a receipt for a CE Unit is received the actual response is incremented and then compared to ceExpectedCapacity. If ceExpectedCapacity is null a null pointer exception was thrown.
Added null check to comparison and moved into separate method.
The acceptance test receipted cases increment ceActualResponses is useful for this. Have a break point set after the sample is loaded for the CE U test and set the ceExpectedCapacity to null in the DB. Let it run and it shouldn't null pointer exception.
https://trello.com/c/EtgoTcNJ/1077-incrementing-actual-response-count-is-broken-if-expected-response-count-is-null
> Check ceExpectedCapacity not null when comparing actual to expected for CE U

- src/main/java/uk/gov/ons/census/casesvc/service/RefusalService.java
- src/test/java/uk/gov/ons/census/casesvc/service/RefusalServiceTest.java
All refusals should now be sent to Fieldwork unless the original message channel is from Fieldwork.
* Remove logic bits for checking "estab case and channel not from field"
* Updated test to check null metadata is sent in outbound message to fieldwork-adapter (which should then ignore the message and not send to Fieldwork)
Run the acceptance tests
https://trello.com/c/u85DtO8j/1045-refusal-table-of-truth-changes-3
> Change refusal for estab case condition

- src/main/resources/application.yml
caesrefgenkey sneaked into application.yml like a sneaky thing 
https://trello.com/c/uVjhAeGK/1143-dont-include-prod-values-which-need-to-be-secret-in-default-config
> remove caseRefGenKey from app.yml

- src/main/java/uk/gov/ons/census/casesvc/model/entity/CaseMetadata.java
- src/main/java/uk/gov/ons/census/casesvc/service/CaseService.java
- src/main/java/uk/gov/ons/census/casesvc/service/FulfilmentRequestService.java
- src/main/java/uk/gov/ons/census/casesvc/service/QuestionnaireLinkedService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/FulfilmentRequestReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/QuestionnaireLinkedReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/SurveyLaunchedReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/CaseServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/FulfilmentRequestServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/QuestionnaireLinkedServiceTest.java
For individual response reminders we need to be able to filter cases down to HI cases created by events from only `EQ`.
* Store the event channel in HI case metadata from fulfilment and PQ link events
* Update tests
* Fix tests failure due to not purging queue
Run with linked AT's and PR branches, see AT PR
https://trello.com/c/Rc8d1RmE/983-reminders-individual-response-8
https://github.com/ONSdigital/census-rm-acceptance-tests/pull/296
> Individual response reminders - store HI case channel in metadata

- src/main/java/uk/gov/ons/census/casesvc/model/dto/CreateCaseSample.java
- src/main/java/uk/gov/ons/census/casesvc/service/EventService.java
- src/main/java/uk/gov/ons/census/casesvc/utility/EventHelper.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/SampleReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/EventServiceTest.java
When adding new addresses from AR as new cases in RM, we don't want them to create uac-qids and we want to send a create message to field when this has happened.
- When new addresses come in from the bulk processor, it creates cases without the uac-qids attached to the case.
- Run with other branches on PR ([toolbox](https://github.com/ONSdigital/census-rm-toolbox/pull/56), terraform and kubernetes). Should be able to put a file in the bucket and once the bulk processor has ran, new cases should be created from the addresses.
[Trello](https://trello.com/c/ATLrBzMk)
[Toolbox](https://github.com/ONSdigital/census-rm-toolbox/pull/56)
[Kubernetes](https://github.com/ONSdigital/census-rm-kubernetes/pull/288)
[Terraform](https://github.com/ONSdigital/census-rm-terraform/pull/186)
> 1183 am file new

- src/main/resources/application.yml
ATs are failing because Notify Processor is too quick and it sends the RM_UAC_CREATED message before the case has been created.
Increased the retry delay from 1 second to 3 seconds.
Run the ATs - they'll probably work locally though - it's only broken in CI.
Trello: https://trello.com/c/RExzTzH3
> Increase retry delay for eventual consistency

- src/main/java/uk/gov/ons/census/casesvc/config/MessageConsumerConfig.java
Having `maxAttempts` set to 1 for the `RetryOperationsInterceptor` didn't seem to retry a failed message even once.
Increased `maxAttempts` from 1 to 2.
It's difficult.
Trello: https://trello.com/c/RExzTzH3
> Increase max retry attempts to 2 because 1 didn't retry

- src/main/java/uk/gov/ons/census/casesvc/service/QidReceiptService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/ReceiptReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/SpringRetryIT.java
- src/test/java/uk/gov/ons/census/casesvc/testutil/DataUtils.java
- src/test/java/uk/gov/ons/census/casesvc/testutil/RabbitQueueHelper.java
"Actual" response count is a very rough figure, built on top of an already horrendously over-complex receipting pile of pain. As such, 'defects' are nonsensical, given that they might affect 2 or 3 respondents in the whole exercise of tens of millions of people.
Only log receipts which have already been receipted.
Don't even bother - waste of time.
Trello: https://trello.com/c/KYgOuyLj
> Only log receipts on already receipted UAC-QIDs

- src/main/java/uk/gov/ons/census/casesvc/model/dto/UacCreatedDTO.java
- src/main/java/uk/gov/ons/census/casesvc/service/UacService.java
- src/test/java/uk/gov/ons/census/casesvc/service/UacServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/testutil/DataUtils.java
Although we don't store batch IDs anywhere - they're transient - we will be able to see all the UACs created by a particular Action (rule or fulfilment) batch, grouped together.
Allow batch ID to be sent, received and stored against any UACs created by RM.
Trigger a reminder rule. All the UACs that get created should have the same batch ID.
Trello: https://trello.com/c/ELepDger
> Allow batch ID to be sent on RM_UAC_CREATED

- src/main/java/uk/gov/ons/census/casesvc/service/FieldCaseUpdatedService.java
- src/main/java/uk/gov/ons/census/casesvc/service/NewAddressReportedService.java
- src/test/java/uk/gov/ons/census/casesvc/service/NewAddressReportedServiceTest.java
We were logging our event JSON inconsistently. We want to log it in a different way, but still inconsistently... but it's hopefully what's been agreed with Rob S and DAP, so it might be OK.
Did the changes requested by Rob S.
Don't bother - there are ITs. DAP will ingest the data eventually and tell is if it's OK for them.
Trello: https://trello.com/c/R3awWPFz
> Tweak logged event JSON to be inconsistent in a different way

- src/main/java/uk/gov/ons/census/casesvc/model/entity/Case.java
For postcode search in ops-ui we need to add an index into the cases table on the postcode column.
- Updated entity to show postcode index
- Run mvn clean install
- Run with other branches
[Trello](https://trello.com/c/qkkjvupd/1221-r-ops-search-for-case-and-show-results-13)
> Add postcode index to entity

- src/main/java/uk/gov/ons/census/casesvc/model/entity/Case.java
The index on the postcode column alone did not aid the postcode search queries.
* Remove index on postcode column
No functional changes here.
https://trello.com/c/fg58euQh/1361-add-a-fancy-pants-index-on-postcode-column-to-speed-up-rops-query-time
> Remove cases postcode index

- src/main/java/uk/gov/ons/census/casesvc/messaging/UnaddressedReceiver.java
- src/main/java/uk/gov/ons/census/casesvc/model/entity/UacQidLink.java
- src/main/java/uk/gov/ons/census/casesvc/model/entity/UacQidLinkMetadata.java
- src/main/java/uk/gov/ons/census/casesvc/service/CCSPropertyListedService.java
- src/main/java/uk/gov/ons/census/casesvc/service/EventService.java
- src/main/java/uk/gov/ons/census/casesvc/service/UacService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/UnaddressedReceiverTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/EventServiceTest.java
- src/test/java/uk/gov/ons/census/casesvc/service/UacServiceTest.java
To make it easier to figure out which UAC was added to a case for what purpose, when dealing with operational issues, it's useful to have the source and channel.
Stamped the source and channel onto UACs when they're created.
Create some UACs via various routes (Contact Centre via Case API, Field via Notify, Reminders via Action Scheduler etc) and check that the source shows up correctly in the database.
Trello: https://trello.com/c/RXayiIFg
> Store source and channel on UACs

- src/main/java/uk/gov/ons/census/casesvc/service/FulfilmentRequestService.java
We get sent loads of garbage during testing. The garbage is annoying. The error message doesn't make it clear exactly _why_ the message is garbage (except that we rejected it - it errors because it's garbage).
Make the "it's garbage" message more explicit about what kind of garbage we got sent.
Send some garbage.
Trello: https://trello.com/c/BlPsX8kS
> Add more helpful error message when we get sent garbage

- src/main/java/uk/gov/ons/census/casesvc/service/RmCaseUpdatedService.java
- src/test/java/uk/gov/ons/census/casesvc/service/RmCaseUpdatedServiceTest.java
When dealing with address updates, if we sent a CREATE action to field for a case that they already know about then it causes them problems.  If an oa value is present for the original case then we need to send an UPDATE action instead.
If the oa is not null on the original case (before address updates have been applied) then we send an UPDATE action instead of a CREATE.
- Run an address update (send a manual message or run the bulk updater from toolbox) for a case that doesn't have an oa value against it.  A CREATE field decision should be sent to field.
- Send another update against the same case. The case will now already have an oa value against it so an UPDATE should be sent to field.
- https://trello.com/c/vlpzyc7c
> Create or update after loading update file

- src/main/java/uk/gov/ons/census/casesvc/service/AddressModificationService.java
- src/main/java/uk/gov/ons/census/casesvc/service/AddressTypeChangeService.java
- src/main/java/uk/gov/ons/census/casesvc/utility/AddressModificationValidator.java
- src/test/java/uk/gov/ons/census/casesvc/utility/AddressModificationValidatorTest.java
I didn't want to do this, but it was too hard for other systems to make the necessary changes, so we had to kludge RM. I don't know. Read the Trello ticket for some background.
Allowed Contact Centre to send an estab type of "OTHER" although it is not one of the allowed ones.
Try sending an address modification with estab type "OTHER" from CC, and it should work. Try sending an address modification with estab type "OTHER" from RH, and it should throw an exception.
Try sending an address type change, with an address modification, with estab type "OTHER" from CC, and it should work. Try sending an an address type change, with an address modification, with estab type "OTHER" from RH, and it should throw an exception.
Trello: https://trello.com/c/ZUuPMYuQ
> Allow Contact Centre to send Estab Type OTHER for modifications and case type change modifications

- src/main/java/uk/gov/ons/census/casesvc/service/RmCaseUpdatedService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/RmCaseUpdatedReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/RmCaseUpdatedServiceTest.java
For reasons too horrible to go into in this PR, we are hacking RM in a deeply regrettable way, as forced to by external teams.
Something so horrible and hacky that it's impossible to explain (and support, and maintain). Read the Trello ticket, but I doubt you'll be any the wiser.
Why even bother? This is so hacky. Nobody knows why this is being done (i.e. what requirement it meets) and nobody can understand the complex scenarios. This a departure from working high-quality software which can be supported and maintained, and will work reliably, into the territory of unsupportable, unreliable, buggy rubbish which won't work.
Trello: https://trello.com/c/i6xdQWau
> Field address update CREATE/UPDATE decision hack

- src/main/java/uk/gov/ons/census/casesvc/service/FieldCaseUpdatedService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/FieldCaseUpdatedReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/FieldCaseUpdatedServiceTest.java
Business requirements have changed.
Only send to field CE units. Send update if the actual response count is greater than the expected response count.
Try updating the case using FIELD_CASE_UPDATED event on CE unit cases. When the actual response count is equal to or greater than the expected response count, the Field case should be cancelled, otherwise it should be updated. Other case types and address levels should either be ignored or throw errors, per prior behaviour.
Trello: https://trello.com/c/E1Qk7n8H
> Send UPDATE to FWMT-G for FieldCaseUpdated (CE Units only)

- src/main/java/uk/gov/ons/census/casesvc/service/NewAddressReportedService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/census/casesvc/messaging/AddressReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/NewAddressReportedServiceTest.java
Field need to be sent new household cases back to them for new addresses
- Removed logic checking for case type in newaddressreported code
- Run `mvn clean install`
- Run with the ATs branch
- Try sending a HH `newaddressreported` with source id from `FIELD`. There should be a create message on the `rm.field` once its been processed
[Trello](https://trello.com/c/TEbkKVfG/)
> 1558-change-logic-to-send-create-messages-to-field-for-household-new-addresses

- src/main/java/uk/gov/ons/census/casesvc/service/FieldCaseUpdatedService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/FieldCaseUpdatedReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/FieldCaseUpdatedServiceTest.java
When the ticket was implemented, it said to send an UPDATE to field when ER > AR. The ticket was then amended, by whom and why is not known. The desired behaviour from product manager is _currently_ at time of writing, to only send CANCEL and never send UPDATE.
Removed UPDATE behaviour.
Don't bother. It's going to go through PO review anyway.
Trello: https://trello.com/c/C7cvRnRv
> Remove sending UPDATE to field when ER > AR

- src/main/java/uk/gov/ons/census/casesvc/service/CCSPropertyListedService.java
- src/test/java/uk/gov/ons/census/casesvc/service/CCSPropertyListedServiceTest.java
The default "don't send to field if..." rules are stopping CCS cases from going to field when they're missing certain data. Apparently we don't want that.
Removed the default rule check from CCS property listed.
Run the new unit test.
Trello: https://trello.com/c/YDlvY9oL
> CCS Property Listed Shouldn't Use Default Rules

- src/main/java/uk/gov/ons/census/casesvc/service/NewAddressReportedService.java
- src/test/java/uk/gov/ons/census/casesvc/service/NewAddressReportedServiceTest.java
The MI team have noticed that we are logging the NEW_ADDRESS_REPORTED event in 2 different ways
Removed method of logging new address through getPayload().getNewAddress()
Fixed tests
Maven Clean Install
Check it builds and tests pass
https://trello.com/c/YjISHq44
https://github.com/ONSdigital/census-rm-case-processor/blob/master/src/main/java/uk/gov/ons/census/casesvc/service/NewAddressReportedService.java#L90
https://github.com/ONSdigital/census-rm-case-processor/blob/master/src/main/java/uk/gov/ons/census/casesvc/service/NewAddressReportedService.java#L131
> NEW_ADDRESS_REPORTED Event Being Logged In 2 Different Ways

- src/main/java/uk/gov/ons/census/casesvc/service/CaseReceiptService.java
- src/test/java/uk/gov/ons/census/casesvc/service/CaseReceiptServiceTableTest.java
UPDATE message being sent to Field when AR > ER which shouldn't happen
Now follows these rules:
- AR < ER (Send UPDATE)
- AR = ER (Send CANCEL)
- AR > ER (Send nothing)
- ER = null (Send nothing)
Build image and run ATs
Load a sample and set the actualResponses/expected and check the variations send (or don't send) the correct output
https://trello.com/c/OEL6bfx5
https://collaborate2.ons.gov.uk/confluence/display/SDC/Receipting
> Receipting Bug Fix When AR > ER

- src/main/java/uk/gov/ons/census/casesvc/model/entity/Case.java
We need speedy look ups on UPRN for case API, this PR adds an index to facilitate.
* Add index to UPRN in case entity
No functional changes. UPRN look up speed should be improved once this is deployed.
https://trello.com/c/XWfypxu8/1874-add-indexes-to-uprn-field-in-cases-db-table-5
https://github.com/ONSdigital/census-rm-case-api/pull/104
https://github.com/ONSdigital/census-rm-ddl/pull/84
> 1874 Add index to UPRN in case entity

- src/main/java/uk/gov/ons/census/casesvc/model/dto/InvalidAddress.java
Specification changed. Nobody told us.
Added `notes` part which was secretly added to [part of the] specification.
Don't even bother. It made it this far without testing finding the issue.
Trello: https://trello.com/c/TlC16P4g
> Add notes to Invalid Address DTO so that we capture them

- src/main/java/uk/gov/ons/census/casesvc/service/CaseService.java
- src/main/java/uk/gov/ons/census/casesvc/service/FulfilmentRequestService.java
- src/test/java/uk/gov/ons/census/casesvc/messaging/FulfilmentRequestReceiverIT.java
- src/test/java/uk/gov/ons/census/casesvc/service/FulfilmentRequestServiceTest.java
There's a bug when we process the same individual fulfilment message more than once, then Hibernate converts the INSERT of new case into an UPDATE, and mangles the data (deletes created timestamp and sets secret sequence number to zero, and then of course, sets case ref to be the same one every single time).
Check if individual case ID already exists; throw exception if it does.
Send an individiual fulfilment. Check that the case has been created. Send the same message AGAIN. This should result in "mangled" case data as described.
Trello: https://trello.com/c/cH8Gw1x2
> Check if indiv case has already beeen created

- src/main/java/uk/gov/ons/census/casesvc/service/AddressTypeChangeService.java
- src/main/java/uk/gov/ons/census/casesvc/service/CaseService.java
- src/main/java/uk/gov/ons/census/casesvc/service/NewAddressReportedService.java
We have a known issue when we are provided with a supposedly new and unique case ID in a message, but the message gets delivered: in this instance, it's likely that we will end up creating a second case with a secretSequenceNumber of zero, and a case ref which has already been used. This behaviour is an annoying aspect of Hibernate trying to be helpful when you ask it to save an entity to the database, and you provide the ID (primary key) of an _existing_ row.
Fixed all the places where this kind of bug might occur (although very unlikely to happen).
Run the ATs. Zero regression.
Trello: https://trello.com/c/6XXXsrvm
> HOTFIX: Fix other places where dupe message might mess up cases
